- name: Set git http_proxy
  git_config:
    - name: http_proxy
      value: "{{ http_proxy }}"
      scope: local
  when: http_proxy is defined

- name: Clone git_roles
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    version: "{{ item.version }}"
    dest: "./roles/{{ item.name }}"
    force: true
  delegate_to: localhost
  with_items: "{{ git_roles }}"
  when: git_roles is defined

- name: Include git_roles
  ansible.builtin.include_role:
    name: "{{ item.name }}"
  with_items: "{{ git_roles }}"
  when: git_roles is defined
